name = "EvenParam"
uuid = "bcb3e14e-248c-11e9-14d9-6db38a995404"
authors = ["Gaspard Jankowiak <gaspard@math.janko.fr>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
